# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: WtCb_Utilities_Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

# Restore and build Web Frontend
  # Restore
    - name: Restore dependencies (Web)
      run: dotnet restore
      working-directory: Wetcardboard_Utilities
    
  # Build
    - name: Build (Web) - Debug
      run: dotnet build --no-restore
      working-directory: Wetcardboard_Utilities
      
    - name: Build (Web) - Release
      run: dotnet build --configuration Release --no-restore
      working-directory: Wetcardboard_Utilities
  
  # Test
    - name: Test (Web)
      run: dotnet test --no-build --verbosity normal
      working-directory: Wetcardboard_Utilities
    
  # Publish
    - name: Publish (Web)
      run: dotnet publish --configuration Release --output ./publish --self-contained true -f net7.0 -r win-x86
      working-directory: Wetcardboard_Utilities
      
  # Secrets
    - name: AppSettings Secrets (Web)
      uses: microsoft/variable-substitution@v1
      with:
        files: Wetcardboard_Utilities/publish/appsettings.Development.json
      env:
        ConnectionStrings.wetcardboard_utilities_mysql: ${{ secrets.PROD_CONNECTIONSTRING_WETCARDBOARD_UTILITIES_MYSQL }}
        Azure.Ad_Login.tenant: ${{ secrets.PROD_AZURE_ADLOGIN_TENANT }}
        Azure.Ad_Login.client_id: ${{ secrets.PROD_AZURE_ADLOGIN_CLIENTID }}
        Azure.Ad_Login.client_secret_timeReg: ${{ secrets.PROD_AZURE_ADLOGIN_CLIENTSECRETTIMEREG }}
        Azure.Ad_Login.Authorization.code_challenge: ${{ secrets.PROD_AZURE_ADLOGIN_AUTHORIZATION_CODECHALLENGE }}
        Azure.Ad_Login.Authorization.code_challenge_method: ${{ secrets.PROD_AZURE_ADLOGIN_AUTHORIZATION_CODECHALLENGEMETHOD }}
        Azure.Ad_Login.Authorization.code_verifier: ${{ secrets.PROD_AZURE_ADLOGIN_AUTHORIZATION_CODEVERIFIER }}
        Jwt.Issuer: ${{ secrets.PROD_JWT_ISSUER }}
        Jwt.Audience: ${{ secrets.PROD_JWT_AUDIENCE }}
        Jwt.Key: ${{ secrets.PROD_JWT_KEY }}
        ApiService_BasePath: ${{ secrets.PROD_APISERVICEBASEPATH }}
    
  # Deploy
    - name: FTP Deploy (Web)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with: 
        server: ${{ secrets.PROD_FTP_SERVER }}
        username: ${{ secrets.PROD_FTP_USERNAME }}
        password: ${{ secrets.PROD_FTP_PASSWORD }}
        server-dir: public_html/Utilities/Web/
        local-dir: Wetcardboard_Utilities/publish/
      
# Restore and build Api Backend
    - name: Restore dependencies (Api)
      run: dotnet restore
      working-directory: Wetcardboard_Utilities_Api
    - name: Build (Api)
      run: dotnet build --no-restore
      working-directory: Wetcardboard_Utilities_Api
    - name: Test (Api)
      run: dotnet test --no-build --verbosity normal
      working-directory: Wetcardboard_Utilities_Api
